mysite/musicbox/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
	url(r'^home/$', views.home, name='home'),
	url(r'^signup/$', views.signup, name='signup'),
	url(r'^signin/$', views.signin, name='signin'),
	url(r'^rating/$', views.ratingList, name='rating'), 
	url(r'^rating/(?P<song_id>\d+)/$', views.songDetails, name='songDetails'), 
	url(r'^home/(?P<song_id>\d+)/$', views.songDetails, name='songDetails'), 
	url(r'^genre/$', views.genre, name='genre'),
	url(r'^genre/(?P<genre_id>\d+)/$', views.songsofgenre, name='songsofgenre'),
	url(r'^about/$', views.about, name='about'),
	url(r'^upload/$', views.upload, name='upload'),
]

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
	url(r'^musicbox/', include('musicbox.urls', namespace = "musicbox")),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/musicbox/models.py
import os
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from utils import get_file_upload_path, get_cover_upload_path
from django.core.files.storage import FileSystemStorage

from django.core.validators import RegexValidator
# from __future__ import unicode_literals

from collections import OrderedDict

from django import forms
from django.contrib.auth import authenticate, get_user_model
#import eyed3 # needed installation


class Genre(models.Model):
    genre_name = models.CharField(max_length=50)
    #genre_type = models.CharField(max_length=50)

    #notes = models.TextField()
    #creation_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return (self.genre_name)

    #class Meta:
     #  ordering = ['genre_name',]

# model for song info(code retrieved from https://github.com/muratcorlu/django-music)
class Song(models.Model):
    #file = models.FileField(_('File'), upload_to=get_file_upload_path)
    title = models.CharField(_('Title'), max_length=100)
    artist = models.CharField(_('Artist'), max_length=100)
    #genre = models.CharField(_('Genre'), max_length=50)
    genre = models.ForeignKey(Genre, null=True)
	
    year = models.CharField(_('Year'), max_length=4, blank=True)
    publisher = models.CharField(_('Publisher'), max_length=100, blank=True)
    rating = models.IntegerField(_('Rating'),default=0)
    overall_rating = models.IntegerField(_('Overall Rating'),default=0)
    #cover_image = models.ImageField(_('Cover image'), upload_to=get_cover_upload_path, blank=True)
    total_rating = models.IntegerField(_('Total Rating'), default=0)
    sumitted_count = models.IntegerField(_('Total Rating Submmited'), default=0)

    play_count = models.IntegerField(_('Play count'), default=0)

    added_date = models.DateTimeField(auto_now_add=True)

    file = models.FileField(upload_to='music', null=True)

    def filename(self):
		return os.path.basename(self.file.name)

    def save(self, *args, **kwargs):
        self.file_size = self.file.size

        super(Song, self).save(*args, **kwargs)

        file_path = os.path.join(settings.MEDIA_ROOT, self.file.name)

        '''
        if eyeD3.isMp3File(file_path):
            audioFile = eyeD3.Mp3AudioFile(file_path)
            self.duration = audioFile.getPlayTime()

            tag = audioFile.getTag()
            self.artist = tag.getArtist()
            self.album = tag.getAlbum()
            self.track_number = tag.getTrackNum()
        '''

        super(Song, self).save(*args, **kwargs)


    def __unicode__(self):
        return "%s" % self.title

class Choice(models.Model):
    rateValue = models.ForeignKey(Song, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


class Music(models.Model):
	file = models.FileField(upload_to='music', null=True, blank = True)
	title = models.CharField(max_length=15)
	genre = models.CharField(max_length=15)
	artist = models.CharField(max_length=15)

	def filename(self):
		return os.path.basename(self.file.name)


# model for user info
class Users(models.Model):
    name_first = models.CharField(max_length=10)
    name_last = models.CharField(max_length=10)
    password = models.CharField(max_length=50)
    repassword = models.CharField(max_length=50)
    email = models.EmailField()
    phone_regex = RegexValidator(regex=r'^1?\D*(\d{3})\D*(\d{3})\D*(\d{4})$', message="phone number must be in the format XXX-XXX-XXXX")
    phone_number = models.CharField(max_length=15, validators=[phone_regex], blank=True) #validators should be a list


    def __unicode__(self):
        return (self.name_first + " " + self.name_last)

mysite/signin/models.py
from django.db import models

class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    email = models.EmailField()
    phone_number = models.CharField(max_length=13)
    
    
    
    def __unicode__(self):
        return '%s ' % (self.username)
    
    

mysite/musicbox/forms.py
from django.forms import ModelForm, CharField, Form, PasswordInput
from django.db import models
from django import forms

from musicbox.models import Song, Users


class SongForm(ModelForm):
	class Meta:
		model = Song
		fields = ('title', 'artist', 'genre', 'year', 'publisher', 'file')
	
	


class UsersForm(ModelForm):
	password = CharField(widget=PasswordInput())
	repassword = CharField(widget=PasswordInput())
	class Meta:
		model = Users

		fields = ('name_first', 'name_last','password','repassword', 'email', 'phone_number')


	def clean_repassword(self):
		password = self.cleaned_data.get('password')
		repassword = self.cleaned_data.get('repassword')
		if not repassword:
			raise forms.ValidationError("You must confirm your password")
		if password != repassword:
			raise forms.ValidationError("Your passwords do not match")
	 	return repassword


class SigninForm(ModelForm):
	password=CharField(widget=PasswordInput())
	class Meta:
		model = Users

		fields = ('email','password')
	def check(self):
		if not email:
			raise forms.ValidationError("You must provide you email address")
		if not pasword:
			raise forms.ValidationError("You must provide you passwords")

class RatingForm(forms.ModelForm):
	rating = forms.ChoiceField(widget=forms.RadioSelect(), choices=[(5, "5"), (4, "4"), (3, "3"), (2, "2"), (1, "1")])

	class Meta:
		model = Song
		fields = ('rating',)

mysite/musicbox/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.db.models import fields
from django.contrib import messages

from musicbox.models import Users, Music, Song, Genre
from musicbox.forms import UsersForm, SigninForm, SongForm, RatingForm

def home(request):
    recommand_list = Song.objects.filter(rating__gte=3)  
    new_list = Song.objects.filter(play_count=0)
    return render(request,'musicbox/home.html', {
        'new_list':new_list,
        'recommand_list': recommand_list
        })

def index(request):
	return render(request,'musicbox/index.html')

def signup(request):
    if request.method == 'POST':
        form = UsersForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Sign up successful!')
            return redirect(reverse('musicbox:signin'))
    else:
        form = UsersForm()

    return render(request,'musicbox/signup.html',{'form': form})
	
def signin(request):
    if request.method == 'POST':
        form = SigninForm(request.POST)
        if form.is_valid():
            useremail = request.POST['email']
            userpassword = request.POST['password']
            try:
                targetuser = Users.objects.filter(email = useremail)
                try:
                    user = Users.objects.get(email = useremail, password = userpassword)
                    messages.success(request, 'Welcome ' + user.name_first + " " + user.name_last + " !")
                    return redirect(reverse('musicbox:home'))
                except:
                    messages.error(request, 'Error: Invalid pasword!')
                    return redirect(reverse('musicbox:signin'))
            except Users.DoesNotExist:
                messages.error(request, 'Error: Invalid email!')
                return redirect(reverse('musicbox:signin'))


            # return redirect(reverse('musicbox:index'))
    else:
        form = SigninForm()

        # userlist = Users.objects.order_by('name_last')
    return render(request,'musicbox/signin.html',{'form': form})
        # return redirect(reverse('musicbox:home'))

def ratingList(request):
    recommand_list = Song.objects.all()
    rated_list = Song.objects.exclude(overall_rating=0)#[:10]
    no_rating = Song.objects.filter(overall_rating=0)

    return render(request,'musicbox/rating.html', {
        'rated_list': rated_list,
        'no_rating':no_rating,
        'recommand_list': recommand_list,
        })

def songDetails(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    if request.method == 'POST':
        form = RatingForm(request.POST or None, instance=song)
        oldrate = song.overall_rating
        if form.is_valid():
            song.sumitted_count += 1
            form.save()
            song.total_rating = song.rating+song.total_rating
            song.overall_rating = song.total_rating//song.sumitted_count
            form.save()
            return redirect(reverse('musicbox:songDetails', args=(song_id)))
    else:
        form = RatingForm(instance=song)
        song.play_count +=1
        song.save()
    return render(request, 'musicbox/songDetails.html', {
        'songdetails': song,
        'form': form
        })

def about(request):
	return render(request,'musicbox/about.html')

def upload(request):
	if request.method == 'POST':
		form = SongForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			messages.success(request, 'Upload successful!')
			return redirect(reverse('musicbox:upload'))
	else:
		form = SongForm()
	return render(request, 'musicbox/upload.html', {'form': form})


def genre(request):
    genre_list = Genre.objects.all()
    return render(request, 'musicbox/genre.html', {'genre_list':genre_list})

def songsofgenre(request, genre_id):
    songsofgenre_list = Song.objects.filter(genre__pk=genre_id)
    genre = Genre.objects.get(pk=genre_id)
    genre_list = Genre.objects.all()
    #songsofgenre_list = Song.objects.filter(genre=genre_id)
    return render(request, 'musicbox/songsofgenre.html', {
        'songsofgenre_list': songsofgenre_list,
        'genre': genre,
        'genre_list': genre_list
        })


def billboard(request):
    chart = billboard.ChartData('hot-100')

    return render(request, 'musicbox/home.html',{'chart': chart})

mysite/signin/views.py
from django.shortcuts import render_to_response
from django.core.context_processors import csrf
from django.http import HttpResponseRedirect
from django.contrib import auth

# Create your views here.
def login(request):
    c={}
    c.update()
    return render_to_response ('login.html' , c)


def auth_view(request):
    username = request.POST.get('username','')
    password = request.POST.get('password','')
    user = auth.authenticate(username=username, password=password)
    
    
    if user is not None:
        auth.login(request, user)
        return HttpResponseRedirect('/accounts/loggedin')
    else:
        return HttpResponseRedirect('/accounts/invalid')

def loggedin(request):
    return render_to_response('loggedin.html',
                              {'user_name' : request.user.username})
def invalid_login(request):
    return render_to_response('invalid_login.html')
def logout(request):
    auth.logout(request)
    return render_to_response('logout.html')

mysite/musicbox/templates/musicbox/about.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>About Us</title>
		<link rel="stylesheet" title="rating" href="{% static 'musicbox/scripts/style3.css' %}" />
		<link href="{% static 'musicbox/scripts/agency.css' %}" rel="stylesheet">
		<link href="{% static 'musicbox/scripts/bootstrap.min.css' %}" rel="stylesheet">
		<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
		<script src="{% static 'musicbox/scripts/application.js' %}"></script>
	</head>
	<body>
		<div id='sitetitle'>
			<span class='siteheader'>
				<h1>Cloud 6 Music Center</h1>
			</span>
		</div>

		<div id="header">
			<ul id="menu">
				<li><a href="{% url 'musicbox:home' %}">Home</a></li>
				<li class="current"><a href="{% url 'musicbox:genre' %}">Genre</a></li>
				<li><a href="{% url 'musicbox:upload' %}">Upload</a></li>
				<li><a href="{% url 'musicbox:rating' %}">Rating</a></li>
				<li class='active'><a href="{% url 'musicbox:about' %}">About</a></li>
			</ul>
		</div>
		<div id="box">
			<div id="about">About us</div>
			<div class="content">			
				<p id="2nd">Cloud 6 is the premier destination for indie music artists to connect with the rest of 
				   the world. We offer<br> a free platform for downloading and uploading songs, and are dedicated to helping 
				   up-and-coming artists <br>be discovered!</p>
				<p id="3rd">Cloud 6 was established in September 2015 by a team of six 
				   hard-working individuals: Fan Liu, Collin Qiao, <br>Janice Sargent, Zhi Chen, Wen Du, and Yuchen Tang. We
				   take great pride in our website, and are even <br>prouder of people who use it.
				</p>
			</div>
		</div>
		    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Your Website 2014</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li>
                        </li>
                        <li>
                        </li>
                        <li>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

	</body>
</html>

mysite/musicbox/templates/musicbox/contact_detail.html
{% extends 'base.html' %}
{% block title %}Genre Details{% endblock %}
{% block content %}

  <h2>{{ contact.genre_name }}</h2>
  <p><b>Genre Type:</b> {{ contact.genre_type }}</p>

  {% if contact.notes %}
  <p><b>Notes:</b> {{ contact.notes }}</p>
  {% endif %}
  <p><b>Created:</b> {{ contact.creation_date|date:"D, m/d/Y" }}</p>

  <p><a href="{% url "edit-contact" contact.id %}">Edit Genre Information</a></p>
  <p><a href="{% url "delete-contact" contact.id %}">Delete Genre</a></p>

{% endblock %}

mysite/musicbox/templates/musicbox/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Rating</title>
	<link rel="stylesheet" title="rating" href="{% static 'musicbox/scripts/style3.css' %}" />
	<link href="{% static 'musicbox/scripts/agency.css' %}" rel="stylesheet">
	<link href="{% static 'musicbox/scripts/bootstrap.min.css' %}" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
	<script src="{% static 'musicbox/scripts/application.js' %}"></script>
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>
<body>
<div id='sitetitle'>
	<span class='siteheader'>
		<h1>Cloud 6 Music Center</h1>
		<h6 id="right"><a href="{% url 'musicbox:index' %}">Logout</a></h6>
	</span>
</div>

<div id="header">
	<ul id="menu">
		<li class='active'><a href="{% url 'musicbox:home' %}">Home</a></li>
		<li class="current"><a href="{% url 'musicbox:genre' %}">Genre</a></li>
		<li><a href="{% url 'musicbox:upload' %}">Upload</a></li>
		<li><a href="{% url 'musicbox:rating' %}">Rating</a></li>
		<li class='last'><a href="{% url 'musicbox:about' %}">About</a></li>
	</ul>
</div>
<div id="messages">
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</div>	

<div class="container">
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="{% static 'musicbox/images/welcom.jpg' %}" alt="Welcom" width="1291" height="400">
      </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

	<div id="billboard" class="container">
		<table id="recommandlist">
			<thead>
				<tr>
					<th>Recommand for You</th>
				</tr>
			</thead>
			<tbody>
				{% if recommand_list %}
					{% for music in recommand_list %}
						<tr>
							<td>{{ forloop.counter }}. <a href="{% url 'musicbox:songDetails' music.id %}">{{ music.title }}</a></td>
						</tr>
					{% endfor %}
				{% else %}
						<tr><td>There is no any music yet. You can go to UPLOAD and upload your own music. </td></tr>
				{% endif%}
			</tbody>
		</table>
		<table id="newlist">
			<thead>
				<tr>
					<th>New Songs</th>
				</tr>
			</thead>
			<tbody>
				{% if new_list %}
					{% for music in new_list %}
						<tr>
							<td>{{ forloop.counter }}. <a href="{% url 'musicbox:songDetails' music.id %}">{{ music.title }}</a></td>
						</tr>
					{% endfor %}
				{% else %}
						<tr><td>There is no any music yet. You can go to UPLOAD and upload your own music. </td></tr>
				{% endif%}
			</tbody>
		</table>

	</div>
	    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Your Website 2014</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li>
                        </li>
                        <li>
                        </li>
                        <li>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>

mysite/musicbox/templates/musicbox/signup.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Register</title>
	<link rel="stylesheet" title="rating" href="{% static 'musicbox/scripts/style3.css' %}" />
	<link href="{% static 'musicbox/scripts/agency.css' %}" rel="stylesheet">
	<link href="{% static 'musicbox/scripts/bootstrap.min.css' %}" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
	<script src="{% static 'musicbox/scripts/application.js' %}"></script>
</head>
<body>
<div id='sitetitle'>
	<span class='siteheader'>
		<h1>Cloud 6 Music Center</h1>
	</span>
</div>
		<div id="signUp" class="container">
		<p>Register Here!</p>
		
		<form action="{% url 'musicbox:signup'  %}" method="post" enctype="multipart/form-data">

		{% csrf_token %}
	    	{{ form.non_field_errors }}
	   	 {% for field in form %}
		<div class="field_container">
		    {{ field.errors }}
		    {{ field.label_tag }} </br>
		    {{ field }}
		</div>
	    {% endfor %}
	 	<a href="{% url 'musicbox:signin' %}"><input type="submit" value="Submit" /></a>
		<a href="{% url 'musicbox:index' %}"><input type="button" value="Cancel" /></a>
	 	 </form>
	</div>
	    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Your Website 2014</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li>
                        </li>
                        <li>
                        </li>
                        <li>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>

mysite/musicbox/templates/musicbox/songDetails.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Rating</title>
	<link rel="stylesheet" title="rating" href="{% static 'musicbox/scripts/style3.css' %}" />
	<link href="{% static 'musicbox/scripts/agency.css' %}" rel="stylesheet">
	<link href="{% static 'musicbox/scripts/bootstrap.min.css' %}" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
	<script src="{% static 'musicbox/scripts/application.js' %}"></script>

</head>
<body>
<div id='sitetitle'>
	<span class='siteheader'>
		<h1>Cloud 6 Music Center</h1>
	</span>
</div>

<div id="header">
	<ul id="menu">
		<li><a href="{% url 'musicbox:home' %}">Home</a></li>
		<li class="current"><a href="{% url 'musicbox:genre' %}">Genre</a></li>
		<li><a href="{% url 'musicbox:upload' %}">Upload</a></li>
		<li class='active'><a href="{% url 'musicbox:rating' %}">Rating</a></li>
		<li class='last'><a href="{% url 'musicbox:about' %}">About</a></li>
	</ul>
</div>
<div id = "song_controller">
	{% if songdetails %}
	<audio controls autoplay>
		<source src={{songdetails.file.url}} type="audio/mpeg">
		Your browser does not support the audio element.
	</audio>
	{% endif %}
</div>
<h2 id="songtitle">{{ songdetails.title }}</h2> 
<div class="section">
		<div class="container">
			<table>
				<tbody>
					<tr><td>Artist: {{ songdetails.artist }}</td></tr>
					<tr><td>Added Date: {{ songdetails.added_date }}</td></tr>
					<tr><td>Listened: {{ songdetails.play_count }}</td></tr>
					<tr><td>Your Rate: <form action="" method="post" enctype="multipart/form-data">
							{% csrf_token %}
							{% for radio in form.rating %}
								{{ radio }}
							{% endfor %}
							<input type="submit" name="submit" value="Submit" />
							<a href="{% url 'musicbox:rating' %}"></a>
						</form></td>
					</tr>
				</tbody>
			</table>
		</div>
</div>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Your Website 2014</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li>
                        </li>
                        <li>
                        </li>
                        <li>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>


</body>

</html>

mysite/musicbox/templates/musicbox/songsofgenre.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Rating</title>
    <link rel="stylesheet" title="rating" href="{% static 'musicbox/scripts/style3.css' %}" />
    <link href="{% static 'musicbox/scripts/agency.css' %}" rel="stylesheet">
    <link href="{% static 'musicbox/scripts/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="{% static 'musicbox/scripts/application.js' %}"></script>
</head>

<body>
<div id='sitetitle'>
    <span class='siteheader'>
        <h1>Cloud 6 Music Center</h1>
    </span>
</div>
<div id="header">
    <ul id="menu">
        <li><a href="{% url 'musicbox:home' %}">Home</a></li>
        <li class='active'><a href="{% url 'musicbox:genre' %}">Genre</a></li>
        <li><a href="{% url 'musicbox:upload' %}">Upload</a></li>
        <li><a href="{% url 'musicbox:rating' %}">Rating</a></li>
        <li class='last'><a href="{% url 'musicbox:about' %}">About</a></li>
    </ul>
</div>
<div class="container"><h1>Genres</h1></div>
<div class="gcontainer">
    <div class="col-sm-2">
        <nav class="nav-sidebar">
        {% if genre_list %}
            <ul id="tab1">
            {% for genre in genre_list %}
                <li><a data-toggle="tab" href="{% url 'musicbox:songsofgenre' genre.id %}" >{{ genre }}</a></li>
            {% endfor %}
            </ul>
        {% endif %}    
        </nav>
    </div>
</div>
<!-- tab content -->
<div class="tab-content">
<div class="tab-pane active text-style" id="tab1">
  <h2>{{ genre }}</h2>
    <!-- new -->
        <div class="container">
        <table id="recommandlist">
            <tbody>
                {% if songsofgenre_list %}
                    {% for music in songsofgenre_list %}
                        <tr>
                            <td>{{ forloop.counter }}. <a href="{% url 'musicbox:songDetails' music.id %}">{{ music.title }}</a></td>
                        </tr>
                    {% endfor %}
                {% else %}
                        <tr><td>There is no any music yet. You can go to UPLOAD and upload your own music. </td></tr>
                {% endif%}
            <hr>
            </tbody>
        </table>
</div>
</div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Your Website 2014</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li>
                        </li>
                        <li>
                        </li>
                        <li>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>


</body>
</html>